# Generated by Django 6.0.4 on 2026-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_apartment_floor_area_sqft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
