# Generated by Django 6.0.4 on 2026-04-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_apartmentimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
