# Generated by Django 6.0.4 on 2026-04-14 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_apartmentimage_image_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(30000000)]),
        ),
    ]
