# Generated by Django 6.0.3 on 2026-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notification_type_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
